---
abstract: 'Push Down Automaton Simple'
author:
  - 'Toshiaki Yokoda <>'
build_requires:
  Test::More: 0.98
configure_requires:
  CPAN::Meta: 0
  CPAN::Meta::Prereqs: 0
  Module::Build: 0.38
dynamic_config: 0
generated_by: 'Minilla/v0.11.0, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: PDA-Simple
no_index:
  directory:
    - t
    - xt
    - inc
    - share
    - eg
    - examples
    - author
    - builder
provides:
  PDA::Simple:
    file: lib/PDA/Simple.pm
    version: 0.01
requires:
  Mouse: v2.1.0
  perl: 5.008005
version: 0.01
x_contributors:
  - 'Toshiaki Yokoda <yokoda@ub12.04svr>'
